import { useState } from 'react'

export const L = {
  fr: {
    online: 'En ligne',
    offline: 'Hors ligne',
    copyIp: "Copier l'adresse IP",
    copied: 'Copié !',
    options: 'Options',
    tagline: 'Régie vidéo sur réseau local',
    prefTheme: 'Thème',
    themeLight: 'Clair',
    themeDark: 'Sombre',
    prefLang: 'Langue',
    prefEncoder: 'Encodage vidéo',
    encoderAuto: 'Auto',
    encoderUnavailable: 'non disponible',
    encoderHint: "S'applique au prochain démarrage des transmetteurs.",
    encoderFallback: 'x264 (repli)',
    issue_spout_missing: "Sender Spout introuvable : l'app source est fermée ou le nom a changé. Reprise automatique à son retour.",
    issue_spout_stalled: "Le sender Spout n'envoie plus d'image (app en pause ou figée).",
    issue_spout_format: "Format de pixel du sender illisible.",
    issue_spout_gpu: "Texture illisible : l'app source tourne sur une autre carte graphique.",
    issue_capture_open: "Impossible d'ouvrir le périphérique (débranché ou déjà utilisé par une autre app).",
    issue_capture_lost: "Périphérique perdu : nouvelle tentative chaque seconde.",
    issue_no_signal: "Pas de signal reconnu sur l'entrée (câble, ou résolution hors des modes broadcast).",
    issue_unknown: "Problème de source (voir le log).",
    encoderFallbackHint: "L'encodeur GPU a échoué sur cette source (voir le log) : repli sur x264 jusqu'au prochain changement d'encodage ou redémarrage de l'app.",
    verLabel: 'Version',
    hostLabel: 'Hostname',
    ipLabel: 'Adresse IP',
    netLabel: 'Réseau',
    netValue: 'LAN · connecté',
    setupLabel: 'Config',
    loadTitle: 'Charger une configuration',
    saveAs: 'Enregistrer sous',
    saveAsTitle: 'Enregistrer la configuration courante sous un nouveau nom',
    saveAsPrompt: 'Nom de la configuration :',
    download: 'Télécharger',
    downloadTitle: 'Télécharger le fichier de configuration actif (.toml)',
    importFile: 'Importer',
    importTitle: 'Importer un fichier de configuration (.toml)',
    emission: 'Émission',
    reception: 'Réception',
    txSection: 'Transmetteur',
    rxSection: 'Récepteur',
    addTxHeader: 'Ajouter un transmetteur',
    addRxHeader: 'Créer un récepteur',
    sendAll: 'Tout envoyer',
    sendAllHint: 'Ouvre un transmetteur pour tous les écrans et Spout disponibles',
    sendAllDisabled: 'Désactivé en mode « Tout envoyer »',
    start: 'Lancer',
    stop: 'Arrêter',
    restart: 'Redémarrer',
    edit: 'Éditer',
    del: 'Supprimer',
    emptyTxTitle: 'Aucun transmetteur',
    emptyTxSub: 'Ajoutez une source à diffuser sur le réseau local.',
    emptyRxTitle: 'Aucun récepteur',
    emptyRxSub: 'Connectez-vous à une machine émettrice du réseau.',
  },
  en: {
    online: 'Online',
    offline: 'Offline',
    copyIp: 'Copy IP address',
    copied: 'Copied!',
    options: 'Options',
    tagline: 'Video control room over the LAN',
    prefTheme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    prefLang: 'Language',
    prefEncoder: 'Video encoding',
    encoderAuto: 'Auto',
    encoderUnavailable: 'not available',
    encoderHint: 'Applies when transmitters next start.',
    encoderFallback: 'x264 (fallback)',
    issue_spout_missing: "Spout sender not found: its app is closed or the name changed. Resumes on its own when it is back.",
    issue_spout_stalled: "The Spout sender sends no more frames (app paused or frozen).",
    issue_spout_format: "The sender's pixel format cannot be read.",
    issue_spout_gpu: "Texture cannot be opened: the source app runs on another graphics card.",
    issue_capture_open: "Cannot open the device (unplugged, or used by another app).",
    issue_capture_lost: "Device lost: retrying every second.",
    issue_no_signal: "No recognised signal on the input (cable, or a resolution outside broadcast modes).",
    issue_unknown: "Source problem (see the log).",
    encoderFallbackHint: 'The GPU encoder failed on this source (see the log): running on x264 until the encoder setting changes or the app restarts.',
    verLabel: 'Version',
    hostLabel: 'Hostname',
    ipLabel: 'IP address',
    netLabel: 'Network',
    netValue: 'LAN · connected',
    setupLabel: 'Setup',
    loadTitle: 'Load a setup',
    saveAs: 'Save as',
    saveAsTitle: 'Save the current setup under a new name',
    saveAsPrompt: 'Setup name:',
    download: 'Download',
    downloadTitle: 'Download the active setup file (.toml)',
    importFile: 'Import',
    importTitle: 'Import a setup file (.toml)',
    emission: 'Emission',
    reception: 'Reception',
    txSection: 'Transmitter',
    rxSection: 'Receiver',
    addTxHeader: 'Add transmitter',
    addRxHeader: 'Create receiver',
    sendAll: 'Send all',
    sendAllHint: 'Opens one transmitter for every available display and Spout source',
    sendAllDisabled: 'Disabled in “Send all” mode',
    start: 'Start',
    stop: 'Stop',
    restart: 'Restart',
    edit: 'Edit',
    del: 'Delete',
    emptyTxTitle: 'No transmitters',
    emptyTxSub: 'Add a source to broadcast over the local network.',
    emptyRxTitle: 'No receivers',
    emptyRxSub: 'Connect to a transmitting machine on the network.',
  },
} as const

export type Lang = keyof typeof L
export type LangStrings = Record<keyof typeof L.fr, string>

export function useLang() {
  const [lang, setLang] = useState<Lang>('fr')
  return { lang, setLang, t: L[lang] }
}
