// SPDX-License-Identifier: AGPL-3.0-or-later

//! Generation of per-instance `kyber_config.toml` files.
//!
//! A transmitter's config is the operator's [`Directory::defaults`] with the
//! transmitter-specific values layered on top:
//!
//! * `[kycontroller].port` — the control-plane port.
//! * `[kycontroller].auth.basic` — a transparent default login is injected when
//!   the operator declared no auth, so the transmitter is reachable (kycontroller
//!   has no anonymous mode). Any operator-provided auth is left untouched.
//! * `[kyavserver].spout_sender` — set for [`Source::Spout`], removed otherwise.
//! * `[kyavserver].encoder` — defaulted to `x264` if the operator left it unset
//!   (AMF crashes on the RX 7800 XT; see project notes).
//!
//! [`Directory::defaults`]: crate::Directory::defaults
//! [`Source::Spout`]: crate::Source::Spout

use toml::Value;

use crate::{Source, Transmitter, DEFAULT_AUTH_PASSWORD, DEFAULT_AUTH_USERNAME};

#[derive(Debug, thiserror::Error)]
pub enum GenError {
    #[error("config key `{0}` exists in defaults but is not a table")]
    NotATable(&'static str),
    #[error("failed to serialize config: {0}")]
    Serialize(#[from] toml::ser::Error),
}

/// Render the `kyber_config.toml` contents for `tx`, layering its values on a
/// clone of `defaults`.
pub fn render_config(tx: &Transmitter, defaults: &toml::Table) -> Result<String, GenError> {
    let mut root = defaults.clone();

    // [kycontroller]: port + transparent default auth
    {
        let kyc = table_mut(&mut root, "kycontroller")?;
        kyc.insert("port".to_string(), Value::Integer(i64::from(tx.port)));

        // kycontroller refuses every connection without a valid login, so an
        // instance with no auth configured would be unreachable. If the operator
        // declared nothing, inject the transparent default basic login.
        if !kyc.contains_key("auth") {
            kyc.insert("auth".to_string(), default_auth());
        }
    }

    // [kyavserver]: encoder default + source pinning
    {
        let kya = table_mut(&mut root, "kyavserver")?;
        kya.entry("encoder")
            .or_insert_with(|| Value::String("x264".to_string()));

        match &tx.source {
            Source::Spout { sender } => {
                kya.insert("spout_sender".to_string(), Value::String(sender.clone()));
            }
            Source::Screen { .. } => {
                // A plain screen grabber must not be pinned to a Spout sender.
                kya.remove("spout_sender");
            }
        }
    }

    let header = format!(
        "# Generated by KyberFrog Server — do not edit by hand.\n\
         # Transmitter: {} (port {})\n\
         # Source: {}\n\n",
        tx.name,
        tx.port,
        tx.source.label(),
    );

    Ok(header + &toml::to_string_pretty(&root)?)
}

/// Borrow (creating if absent) a top-level table inside `root`.
fn table_mut<'a>(
    root: &'a mut toml::Table,
    key: &'static str,
) -> Result<&'a mut toml::Table, GenError> {
    root.entry(key)
        .or_insert_with(|| Value::Table(toml::Table::new()))
        .as_table_mut()
        .ok_or(GenError::NotATable(key))
}

/// The `auth` table holding the transparent default basic login (password is
/// stored as the hex SHA-256 of the plaintext, matching kycontroller).
fn default_auth() -> Value {
    let mut login = toml::Table::new();
    login.insert(
        "username".to_string(),
        Value::String(DEFAULT_AUTH_USERNAME.to_string()),
    );
    login.insert(
        "password".to_string(),
        Value::String(sha256_hex(DEFAULT_AUTH_PASSWORD)),
    );

    let mut basic = toml::Table::new();
    basic.insert(
        "logins".to_string(),
        Value::Array(vec![Value::Table(login)]),
    );

    let mut auth = toml::Table::new();
    auth.insert("basic".to_string(), Value::Table(basic));
    Value::Table(auth)
}

/// Hex-encoded SHA-256 of `plaintext` (kycontroller's basic-auth password form).
fn sha256_hex(plaintext: &str) -> String {
    use sha2::{Digest, Sha256};
    hex::encode(Sha256::digest(plaintext.as_bytes()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tx_spout() -> Transmitter {
        Transmitter {
            name: "stage-left".to_string(),
            port: 8080,
            source: Source::Spout {
                sender: "Spout Sender".to_string(),
            },
        }
    }

    fn tx_screen() -> Transmitter {
        Transmitter {
            name: "stage-right".to_string(),
            port: 8081,
            source: Source::Screen { display: None },
        }
    }

    #[test]
    fn spout_pins_sender_and_sets_port() {
        let out = render_config(&tx_spout(), &toml::Table::new()).unwrap();
        let parsed: toml::Table = out.parse().unwrap();
        let kya = parsed["kyavserver"].as_table().unwrap();
        assert_eq!(kya["spout_sender"].as_str(), Some("Spout Sender"));
        assert_eq!(kya["encoder"].as_str(), Some("x264"));
        let kyc = parsed["kycontroller"].as_table().unwrap();
        assert_eq!(kyc["port"].as_integer(), Some(8080));
    }

    #[test]
    fn screen_drops_inherited_spout_sender() {
        let mut defaults = toml::Table::new();
        let mut kya = toml::Table::new();
        kya.insert(
            "spout_sender".to_string(),
            Value::String("Leftover".to_string()),
        );
        defaults.insert("kyavserver".to_string(), Value::Table(kya));

        let out = render_config(&tx_screen(), &defaults).unwrap();
        let parsed: toml::Table = out.parse().unwrap();
        let kya = parsed["kyavserver"].as_table().unwrap();
        assert!(kya.get("spout_sender").is_none());
    }

    #[test]
    fn operator_encoder_default_is_preserved() {
        let mut defaults = toml::Table::new();
        let mut kya = toml::Table::new();
        kya.insert("encoder".to_string(), Value::String("amf".to_string()));
        defaults.insert("kyavserver".to_string(), Value::Table(kya));

        let out = render_config(&tx_spout(), &defaults).unwrap();
        let parsed: toml::Table = out.parse().unwrap();
        assert_eq!(
            parsed["kyavserver"]["encoder"].as_str(),
            Some("amf"),
            "explicit operator encoder must win over the x264 default"
        );
    }
}
